### PR TITLE
Dp 63

### PR DESCRIPTION
**Pull request by kentare**
What is done:

Created DB docker container 
Created DB connection as singleton for servlets
Created DAO example
Created Servlet example
Created Model example

### CODE REVIEW

**Comment by jonwanundsen** [comment]
Comments:
Some of the variable names in MongoDBContextListener use UpperCamelCase instead of lowerCamelCase

It's conventional to use lowercase letters in package names (dao vs. DAO)

I think we should avoid hard coding passwords etc. if possible (in web.xml and elsewhere). If we can make it work, I would prefer to use local configuration files that aren't checked into Git, environment variables, or something along those lines.

MongoUserDao.collection should be parametrized, since MongoCollection is a generic type.

It would be nice to have a little more documentation. I think all public and protected methods should have Javadoc-style documentation (unless their purpose is really obvious, e.g. User.getUsername), including a description of their arguments and what they return, if anything. Classes/interfaces should usually also have a description.

IMO, User.toJavaObject shouldn't change the state of the instance on which it is called, but rather construct and return a new object. To be honest, I think it would be better to make it a static method, but that obviously won't work if it's an abstract method in IUser.

I think it's better to use context.log than to use System.out.println in MongoDBContextListener.

If you write 'throw new RuntimeException("Mongoclient initialization failed", error)' instead of 'throw new RuntimeException("Mongoclient initialization failed")' in MongoDBContextListener.java, 'error' will be registered as the cause of the RuntimeException, which should make the stacktrace a little more useful.

We should probably use no.digipat.patornat as a prefix for package names instead of just no.digipat. E.g.: no.digipat.patornat.mongodb.models.

In line 28 of MongoDBContextListener.java, it's not necessary to call servletContextEvent.getServletContext(), since the context is already stored in the 'context' variable. It's not super important, but the code would be a little more concise if the variable were reused.

I don't understand what the line "/" in .gitignore is supposed to do.

**Comment by kentare** [comment]
1. ```Some of the variable names in MongoDBContextListener use UpperCamelCase instead of lowerCamelCase```
Agreed, that was weird

2. ```It's conventional to use lowercase letters in package names (dao vs. DAO)```
Will fix


3. ```I think we should avoid hard coding passwords etc. if possible (in web.xml and elsewhere). If we can make it work, I would prefer to use local configuration files that aren't checked into Git, environment variables, or something along those lines.```
Will change these to environment variables

4. ```MongoUserDao.collection should be parametrized, since MongoCollection is a generic type.```
I dont understand what this, can you explain?

5. ```It would be nice to have a little more documentation. I think all public and protected methods should have Javadoc-style documentation (unless their purpose is really obvious, e.g. User.getUsername), including a description of their arguments and what they return, if anything. Classes/interfaces should usually also have a description.```
Yes, will add better documentation. 

6. ```IMO, User.toJavaObject shouldn't change the state of the instance on which it is called, but rather construct and return a new object. To be honest, I think it would be better to make it a static method, but that obviously won't work if it's an abstract method in IUser.```
Agreed, this should be in a static method/class. The user model and userDAO is examples for how to interact with the db, none of these are final and will probably not be in deployment. When I start on the relevant user I will probably remove the current state

7. ```I think it's better to use context.log than to use System.out.println in MongoDBContextListener.```
Will check this out 

8. ```If you write 'throw new RuntimeException("Mongoclient initialization failed", error)' instead of 'throw new RuntimeException("Mongoclient initialization failed")' in MongoDBContextListener.java, 'error' will be registered as the cause of the RuntimeException, which should make the stacktrace a little more useful.```
Agreed, will throw exception instead

9. ```We should probably use no.digipat.patornat as a prefix for package names instead of just no.digipat. E.g.: no.digipat.patornat.mongodb.models.```
agreed, will fix this.

10. ```In line 28 of MongoDBContextListener.java, it's not necessary to call servletContextEvent.getServletContext(), since the context is already stored in the 'context' variable. It's not super important, but the code would be a little more concise if the variable were reused.```
100% correct, will fix


11. ```I don't understand what the line "/" in .gitignore is supposed to do.```
A mistake, will fix. 

I will go through and fix these issues tomorrow evening after work

**Comment by jonwanundsen** [comment]
>I dont understand what this, can you explain?

MongoCollection has a type parameter (called TDocument in the official documentation) which specifies the type it can encode and decode documents to and from. Since the constructor for MongoUserDAO sets collection to an instance of the type MongoCollection<Document>, we could change the declaration of collection to the following:
`private MongoCollection<Document> collection;`
This will ensure type safety, and will also ensure that Maven and Eclipse (and, I would assume, IntelliJ) stop giving warnings about this.

**Comment by kentare** [comment]
I have now fixed and refactored everything mentioned in the remarks

**Comment by kentare** [comment]
@jonwanundsen I have added env variables to docker now. Merge the pull request if it looks OK. 

Note: I have not added environment variables to init-mongo.js, the reason is simply that I did not manage to do it successfully. I will visit this problem again in the future.

**Pull request merged**
